language: node_js

node_js:
  - "10.14.2"

cache:
directories:
  - "node_modules"

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=d48769aaf8fb30dd1da8d72885ce531fe994df3003e2e8ca5b1e1337c4f02ef3
    
before_script:
  - psql -c 'create database Questioner;' -U postgres
  -npm run create

script:
  - npm run test 

after_script: 
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT